### ISSUE TITLE
Playground shows error and doesn't seem to work

### ISSUE THREAD

**Issue by willhoney7** [rickbutton/record-tuple-playground#1]
Hi there! I wanted to try out the playground but it doesn't appear to be working. Thanks! (Also, I wasn't sure if I should create the issue here or in the proposal repo... but here it is)

![image](https://user-images.githubusercontent.com/290380/79001296-73731500-7b0b-11ea-9fd8-56b0018d587b.png)

`"WeakMap, WeakRef, and FinalizationRegistry are required for @bloomberg/record-tuple-polyfill"
Error {}`

**Comment by rickbutton** [comment]
This was a recent change when the polyfill moved to an implementation that uses WeakMap, WeakRef, and FinalizationRegistry. These ECMAScript features are still very new and are shipped behind a flag in browsers. In Chrome, run with these flags (assuming Mac since the screenshot is a Mac):

```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --js-flags="--harmony-weak-refs"
```

I should probably add steps for this to the playground, or at least the documentation.

**Comment by rickbutton** [comment]
I've updated the playground to provide a better error message for this, and link to the documentation that has the correct flags for each supported environment.

**Comment by willhoney7** [comment]
Thanks!
